# Generated by Django 3.2.7 on 2021-12-08 09:39

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(max_length=1500, verbose_name='Caption')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
