# Generated by Django 3.2.7 on 2021-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimsta', '0002_auto_20211208_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Dislike', 'Dislike'), ('Like', 'Like')], default='like', max_length=10),
        ),
    ]
